---
version: 2
jobs:
  build:
    working_directory: ~/code_industry
    docker:
      - image: circleci/ruby:2.4.5
        environment:
          PGHOST: localhost
          PGUSER: code_industry
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: code_industry
          POSTGRES_DB: code_industry
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: code_industry_{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: sudo gem update --system
      - run: sudo gem uninstall bundler
      - run: sudo rm /usr/local/bin/bundle
      - run: sudo gem install bundler
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: code_industry{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
